### ISSUE TITLE
Intel Questa Lite version build issue with some testcases

### ISSUE THREAD

**Issue by JasonAtTomra** [OSVVM/OsvvmLibraries#16] opened 2022-10-26 10:10 UTC
vsim -t ps -lib osvvm_TbAxi4 TbAxi4_MemoryBurst1 -suppress 8683 -suppress 8684 
Start time: 10:02:03 on Oct 26,2022
** Note: (vsim-3812) Design is being optimized...
** Error: c:/sandbox/osvvmLibraries/AXI4/Axi4/TestCases/TbAxi4_MemoryBurst1.vhd(214): Protected type method was not invoked on a class VARIABLE object.
** Error: c:/sandbox/osvvmLibraries/AXI4/Axi4/TestCases/TbAxi4_MemoryBurst1.vhd(214): Protected type method was not invoked on a class VARIABLE object.
** Note: c:/sandbox/osvvmLibraries/AXI4/Axi4/TestCases/TbAxi4_MemoryBurst1.vhd(214): Vopt Compiler exiting
** Error: (vopt-2064) Compiler back-end code generation process terminated with code 2.
** Note: (vsim-12126) Error and warning message counts have been restored: Errors=3, Warnings=0.
Error loading design
End time: 10:02:06 on Oct 26,2022, Elapsed time: 0:00:03
Errors: 3, Warnings: 0
1

**Comment by JimLewis** [comment] 2022-10-26 15:55
Thanks for the bug report.

I chased this one earlier this month.   It resolved to a Questa bug.   There is a work around in the Dev branch.  It will be released with 2022.10 (which may be early November).  

Root cause is the following code.  Interestingly it looks like I had 
modified it in the past to work around a different Questa bug.
```vhdl
  ------------------------------------------------------------
  procedure PushBurstRandom (
  ------------------------------------------------------------
    constant Fifo         : in    ScoreboardIdType ;
    constant FirstWord    : in    integer ;
    constant Count        : in    integer ;
    constant FifoWidth    : in    integer := 8
  ) is
    variable RV : RandomPType ; 
    variable intFirstWord : integer ; 
    variable slvFirstWord : std_logic_vector(FifoWidth-1 downto 0) ; 
  begin
    if FirstWord < 0 then 
      intFirstWord := -FirstWord ; 
    else
      intFirstWord := FirstWord ; 
    end if ; 
    
    -- Initialize seed and toss first random value  
    RV.InitSeed(intFirstWord mod 2**30 + Count, UseNewSeedMethods => TRUE) ;
    
    if FifoWidth < NUMBER_POSITIVE_INTEGER_BITS then 
      Push(Fifo, to_slv(intFirstWord mod (2**FifoWidth), FifoWidth)) ;
    else 
      Push(Fifo, to_slv(intFirstWord, FifoWidth)) ;
    end if ; 
    
    for i in 2 to Count loop 
      -- Extra Var added for QuestaSim
      slvFirstWord := RV.RandSlv(FifoWidth) ;
      Push(Fifo, slvFirstWord) ;
    end loop ;
  end procedure PushBurstRandom ;
```

As a result, I replaced the code with a call to the other 
version of PushBurstRandom:
``` vhdl
```

**Comment by JimLewis** [comment] 2022-11-04 23:44
There is a work around for the Questa bug in the upcoming 2022.10 release.

**Closed by JimLewis** 2022-11-04 23:44 UTC
